services:
  # La "fuente de la Verdad" (Consistencia ACID)
  postgres:
    image: postgres:18-alpine
    container_name: lab-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: lab_db
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: lab-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lab.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "80:80"
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    container_name: lab-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
  