import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Account {
  // auto generated by typeorm
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'varchar', nullable: false })
  owner: string;

  @Column({ type: 'integer', nullable: false })
  balance: number;
}
