import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class Payment {
  // auto generated by typeorm
  @PrimaryGeneratedColumn()
  id: number;

  @Column({ type: 'integer', nullable: false })
  account_id: number;

  @Column({ type: 'integer', nullable: false })
  amount: number;

  @Column({ type: 'varchar', nullable: false })
  status: string;

  @CreateDateColumn({ type: 'timestamp' , default: () => 'CURRENT_TIMESTAMP', nullable: false })
  created_at: Date;
}
