import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export class Product {
  // auto generated by typeorm
  @PrimaryGeneratedColumn()
  id: number; 

  @Column()
  name: string;

  @Column()
  stock: number;

}